security:
  cas:
    server:
      base-url: https://apr-test.ebc.edu.mx/casad
    service:
      base-url: http://localhost:8090
spring:
  datasource:
    url: jdbc:oracle:thin:@10.31.23.34:1521:DEVL8
    driver-class-name: oracle.jdbc.OracleDriver
    username: pgocomis
    password: l4bboc1
    jpa:
      database-platform: org.hibernate.dialect.Oracle9iDialect
    configuration:
      maximum-pool-size: 30
db2:
  datasource:
    url: jdbc:oracle:thin:@10.31.23.34:1521:TEST8
    driver-class-name: oracle.jdbc.OracleDriver
    username: admseg
    password: j4n1t0r3es
    jpa:
      database-platform: org.hibernate.dialect.Oracle9iDialect
    configuration:
      maximum-pool-size: 30
banner:
  datasource:
    url: jdbc:oracle:thin:@10.31.23.34:1521:DEVL8
    driver-class-name: oracle.jdbc.OracleDriver
    username: apibanner
    password: ap1b4nn3rd3vl8
    jpa:
      database-platform: org.hibernate.dialect.Oracle9iDialect
    configuration:
      maximum-pool-size: 30
