/*
REM **************************************************************************
REM Nombre del Script: ca_user_campus.sql
REM Proyecto: api-comisiones
REM --------------------------------------------------------------------------
REM AUDIT TRAIL:  Version 1
REM Realizado por: VMRB, 27  de Mayo  de 2019
*/


CREATE TABLE USER_CAMPUS(
  CAMPUS_CODE VARCHAR2(10) NOT NULL,
  USER_NAME VARCHAR2(250) NOT NULL,
  PIDM NUMBER NOT NULL,
  DATE_CREATED DATE NOT NULL,
  LAST_UPDATED DATE,
  CONSTRAINT USER_CAMPUS_PK PRIMARY KEY
  (
    CAMPUS_CODE,
    USER_NAME,
    PIDM
  )
  ENABLE
);


CREATE TABLE PROGRAM_MANAGER(
  PIDM NUMBER NOT NULL,
  USER_NAME VARCHAR2(20) NOT NULL,
  RECR_CODE VARCHAR2(4) NOT NULL,
  CONSTRAINT PROGRAM_MANAGER_PK PRIMARY KEY
  (
    PIDM,
    USER_NAME,
    RECR_CODE
  )
  ENABLE
);

CREATE TABLE PROMOTER(
  PIDM NUMBER NOT NULL,
  USER_NAME VARCHAR2(20) NOT NULL,
  RECR_CODE VARCHAR2(4) NOT NULL,
  PIDM_MANAGER NUMBER,
  USER_NAME_MANAGER VARCHAR2(20),
  RECR_CODE_MANAGER VARCHAR2(4),
  CONSTRAINT PROMOTER_PK PRIMARY KEY
  (
    USER_NAME,
    PIDM,
    RECR_CODE
  ),
  CONSTRAINT PROMOTER_FK FOREIGN KEY
  (
    PIDM_MANAGER,
    USER_NAME_MANAGER,
    RECR_CODE_MANAGER
  )
  REFERENCES PROGRAM_MANAGER
  (
    PIDM,
    USER_NAME,
    RECR_CODE
  )
  ENABLE
);
