/*
REM **************************************************************************
REM Nombre del Script: ca_user_campus.sql
REM Proyecto: api-comisiones
REM --------------------------------------------------------------------------
REM AUDIT TRAIL:  Version 1
REM Realizado por: VMRB, 27  de Mayo  de 2019
*/

DROP TABLE PGOCOMIS.ASOCIACION_PROMOTOR;

CREATE TABLE PGOCOMIS.USER_CAMPUS(
  CAMPUS_CODE VARCHAR2(10) NOT NULL,
  USER_NAME VARCHAR2(250) NOT NULL,
  PIDM NUMBER NOT NULL,
  DATE_CREATED DATE NOT NULL,
  LAST_UPDATED DATE,
  CONSTRAINT USER_CAMPUS_PK PRIMARY KEY
  (
    CAMPUS_CODE,
    USER_NAME,
    PIDM
  )
  ENABLE
);


CREATE TABLE PGOCOMIS.PROGRAM_MANAGER(
  PIDM NUMBER NOT NULL,
  USER_NAME VARCHAR2(20) NOT NULL,
  RECR_CODE VARCHAR2(4) NOT NULL,
  CONSTRAINT PROGRAM_MANAGER_PK PRIMARY KEY
  (
    PIDM,
    USER_NAME,
    RECR_CODE
  )
  ENABLE
);

CREATE TABLE PGOCOMIS.ASOCIACION_PROMOTOR(
  PIDM NUMBER NOT NULL,
  USER_NAME VARCHAR2(20) NOT NULL,
  RECR_CODE VARCHAR2(4) NOT NULL,
  PIDM_MANAGER NUMBER,
  USER_NAME_MANAGER VARCHAR2(20),
  RECR_CODE_MANAGER VARCHAR2(4),
  ID_COORDINADOR VARCHAR2(100),
  NOMBRE_COORDINADOR VARCHAR2(100),
  APELLIDOS_COORDINADOR VARCHAR2(100),
  CLAVE_EMP_COORDINADOR VARCHAR2(100),
  CAMPUS_CODE VARCHAR2(255),
  CAMPUS_DESC VARCHAR2(255),
  ID_PROMOTOR VARCHAR2(255),
  NOMBRE_PROMOTOR VARCHAR2(255),
  APELLIDOS_PROMOTOR VARCHAR2(255),
  CLAVE_EMP_PROMOTOR VARCHAR2(100),
  PUESTO_PROMOTOR VARCHAR2(100),
  RELACION_ACTIVA VARCHAR2(4),
  USUARIO VARCHAR2(255),
  LAST_UPDATED DATE,
  CONSTRAINT ASOCIACION_PROMOTOR_PK PRIMARY KEY
  (
    USER_NAME,
    PIDM,
    RECR_CODE
  ),
  CONSTRAINT ASOCIACION_PROMOTOR_FK FOREIGN KEY
  (
    PIDM_MANAGER,
    USER_NAME_MANAGER,
    RECR_CODE_MANAGER
  )
  REFERENCES PROGRAM_MANAGER
  (
    PIDM,
    USER_NAME,
    RECR_CODE
  )
  ENABLE
);

ALTER TABLE PGOCOMIS.AUTORIZACION_COMISIONES MODIFY AUTORIZADO_DIRECTOR VARCHAR2(255);

CREATE TABLE PGOCOMIS.CAMPAING(
  ID NUMBER,
  STATUS VARCHAR(255),
  INIT_DATE DATE,
  END_DATE DATE,
  NAME VARCHAR(255),
  CLAVE VARCHAR(255),
  USERNAME VARCHAR(100),
  DATE_CREATED DATE,
  LAST_UPDATED DATE,
  CONSTRAINT PK_CAMPAING PRIMARY KEY (ID)
);

CREATE SEQUENCE "NOMINA"."SQ_ID_CAMPAING"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;

CREATE TABLE PGOCOMIS.GOAL(
  ID NUMBER,
  STATUS VARCHAR(255),
  TYPE VARCHAR(255),
  CAMPUS VARCHAR(20),
  NUM_REGISTERS NUMBER,
  PERCENT_COMMISSION NUMBER,
  USERNAME VARCHAR(100),
  DATE_CREATED DATE,
  LAST_UPDATED DATE,
  CAMPAING_ID NUMBER,
  CONSTRAINT PK_GOAL PRIMARY KEY (ID)
);

ALTER TABLE PGOCOMIS.GOAL
  ADD CONSTRAINT CAMPAING_FK
      FOREIGN KEY (CAMPAING_ID)
      REFERENCES PGOCOMIS.CAMPAING(ID);

CREATE SEQUENCE "NOMINA"."SQ_ID_GOAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1;